#!/usr/bin/env python3
"""Ragnar DNS tunnel: persistent keys, direct UDP binding, and end-to-end diagnostics."""
import argparse
import datetime as dt
import fcntl
import ipaddress
import json
import os
from pathlib import Path
import re
import shutil
import socket
import struct
import subprocess
import sys
import tempfile
import time

ROOT = Path('/etc/dnstt')
SERVER = '/usr/local/bin/dnstt-server'
CLIENT = '/usr/local/bin/dnstt-client'
UNIT = Path('/etc/systemd/system/dnstt-server.service')
LEGACY_UNIT = Path('/etc/systemd/system/ragnar-iptables.service')
RULES_FILE = Path('/etc/iptables/rules.v4')
SERVICE = 'dnstt-server.service'
# Remove only the exact redirect generated by previous Ragnar versions.
LEGACY_RULE = ['-p', 'udp', '--dport', '53', '-j', 'REDIRECT', '--to-ports', '5300']


def dns_name(value):
    value = value.rstrip('.').lower()
    if len(value) > 180 or '.' not in value or any(
        not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label) for label in value.split('.')
    ):
        raise ValueError('Enter a full DNS hostname, not a URL, wildcard or shell expression.')
    return value


def ipv4(value):
    addr = ipaddress.IPv4Address(value)
    if addr.is_unspecified or addr.is_multicast or addr.is_loopback or addr.is_link_local:
        raise ValueError('Use a non-loopback IPv4 address, not 0.0.0.0.')
    return str(addr)


def local_ipv4s():
    result = subprocess.run(['ip', '-j', '-4', 'addr', 'show'], check=True, capture_output=True, text=True, timeout=10)
    return [addr['local'] for iface in json.loads(result.stdout) for addr in iface.get('addr_info', [])
            if addr.get('scope') == 'global' and addr.get('family') == 'inet']


def atomic(path, data, mode=0o600):
    fd, name = tempfile.mkstemp(prefix='.' + path.name, dir=str(path.parent))
    try:
        with os.fdopen(fd, 'wb') as out:
            out.write(data)
            out.flush()
            os.fsync(out.fileno())
            os.fchmod(out.fileno(), mode)
        os.replace(name, path)
    finally:
        if os.path.exists(name):
            os.unlink(name)


def read_key(path):
    value = path.read_text().strip()
    if not re.fullmatch(r'[0-9a-fA-F]{64}', value):
        raise ValueError('Invalid dnstt key file: {}'.format(path.name))
    return bytes.fromhex(value)


def derive_public(private):
    # X25519 PKCS#8 encoding. openssl derives the matching public key without
    # exposing the private key in argv, logs, or temporary files.
    der = bytes.fromhex('302e020100300506032b656e04220420') + private
    result = subprocess.run(['openssl', 'pkey', '-inform', 'DER', '-pubout', '-outform', 'DER'],
                            input=der, capture_output=True, timeout=10)
    if result.returncode or len(result.stdout) != 44:
        raise ValueError('Unable to verify the X25519 keypair with openssl.')
    return result.stdout[-32:]


def ensure_keys(root=ROOT, server=SERVER):
    private, public = root / 'server.key', root / 'server.pub'
    if not private.exists():
        if public.exists():
            raise ValueError('Private key missing but public key exists. Restore the private key; keys were not rotated.')
        with tempfile.TemporaryDirectory(prefix='.keys-', dir=str(root)) as work:
            key, pub = Path(work) / 'key', Path(work) / 'pub'
            subprocess.run([server, '-gen-key', '-privkey-file', str(key), '-pubkey-file', str(pub)],
                           check=True, capture_output=True, timeout=10)
            if derive_public(read_key(key)) != read_key(pub):
                raise ValueError('Generated keypair does not match.')
            atomic(private, key.read_bytes())
            atomic(public, pub.read_bytes())
    expected = derive_public(read_key(private))
    if not public.exists():
        atomic(public, (expected.hex() + '\n').encode())
    if read_key(public) != expected:
        raise ValueError('Existing public/private keys do not match. Restore the correct pair; no keys were replaced.')
    private.chmod(0o600)
    public.chmod(0o600)
    return expected.hex()


def validate_config(config):
    config = dict(config)
    config['zone'] = dns_name(config['zone'])
    config['nameserver'] = dns_name(config['nameserver'])
    if config['nameserver'] == config['zone'] or config['nameserver'].endswith('.' + config['zone']):
        raise ValueError('Place the nameserver outside the delegated tunnel zone to avoid circular delegation.')
    config['public_ip'] = ipv4(config['public_ip'])
    config['bind_ip'] = ipv4(config['bind_ip'])
    config['mtu'] = int(config.get('mtu', 1232))
    if not 512 <= config['mtu'] <= 1232:
        raise ValueError('DNS response MTU must be between 512 and 1232.')
    return config


def server_args(config, root=ROOT, binary=SERVER):
    config = validate_config(config)
    return [binary, '-udp', config['bind_ip'] + ':53', '-mtu', str(config['mtu']),
            '-privkey-file', str(root / 'server.key'), config['zone'], '127.0.0.1:22']


def strip_legacy_rules(content):
    """Leave unrelated tables/rules/comments byte-for-byte intact."""
    lines = []
    import shlex
    for line in content.splitlines(keepends=True):
        parts = shlex.split(line, comments=True)
        if parts in (['-A', 'PREROUTING'] + LEGACY_RULE,
                     ['-A', 'PREROUTING', '-p', 'udp', '-m', 'udp'] + LEGACY_RULE[2:]):
            continue
        lines.append(line)
    return ''.join(lines)


def service(action, name=SERVICE, check=True):
    return subprocess.run(['systemctl', action, name], check=check, timeout=45)


def udp_probe(zone, address, port=53):
    # Deliberately invalid tunnel encoding: dnstt must return authoritative
    # NXDOMAIN for this name. This is a DNS reachability check, not authentication.
    qname = b''.join(bytes([len(label)]) + label.encode() for label in ('_ragnar.' + zone).split('.')) + b'\0'
    ident = os.urandom(2)
    packet = ident + struct.pack('!HHHHH', 0x0100, 1, 0, 0, 0) + qname + struct.pack('!HH', 16, 1)
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.settimeout(3)
        sock.connect((address, port))
        sock.send(packet)
        data = sock.recv(4096)
    if len(data) < 12 or data[:2] != ident:
        raise ValueError('Invalid DNS response.')
    flags = struct.unpack('!H', data[2:4])[0]
    if flags & 0x8400 != 0x8400 or flags & 15 != 3:
        raise ValueError('DNS answered, but not as the expected authoritative tunnel endpoint.')


def tunnel_banner(config, root=ROOT, client=CLIENT, resolver=None, timeout=12):
    """Authenticate with the real dnstt client and require the upstream SSH banner."""
    with socket.socket() as sock:
        sock.bind(('127.0.0.1', 0))
        port = sock.getsockname()[1]
    resolver = resolver or config['bind_ip'] + ':53'
    with tempfile.TemporaryFile(dir=str(root)) as log:
        process = subprocess.Popen([client, '-udp', resolver, '-pubkey-file', str(root / 'server.pub'),
                                    config['zone'], '127.0.0.1:' + str(port)], stdout=log, stderr=log)
        try:
            deadline = time.monotonic() + timeout
            while time.monotonic() < deadline:
                if process.poll() is not None:
                    raise ValueError('dnstt-client exited. Check its installation and public key.')
                try:
                    connection = socket.create_connection(('127.0.0.1', port), timeout=.3)
                    break
                except OSError:
                    time.sleep(.1)
            else:
                raise ValueError('DNS client did not start.')
            with connection:
                connection.settimeout(max(1, deadline - time.monotonic()))
                banner = connection.recv(255)
                if not banner.startswith(b'SSH-'):
                    raise ValueError('Authenticated tunnel did not return an SSH banner.')
            return banner.decode('ascii', errors='replace').strip()
        finally:
            process.terminate()
            try:
                process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()


UNIT_TEXT = '''[Unit]
Description=Ragnar DNS tunnel (direct UDP 53 to SSH)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
UMask=0077
ExecStart=/usr/local/bin/ragnar-dns serve
Restart=on-failure
RestartSec=3
NoNewPrivileges=true
PrivateTmp=true
ProtectHome=true
ProtectSystem=strict
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

[Install]
WantedBy=multi-user.target
'''


class DNSManager:
    def __init__(self, root=ROOT, unit=UNIT, server=SERVER, client=CLIENT):
        self.root, self.unit, self.server, self.client = root, unit, server, client
        self.state_path = root / 'ragnar.json'

    def load(self):
        if not self.state_path.exists():
            raise ValueError('DNS tunnel not configured. Use menu -> 9 -> Install/repair.')
        return validate_config(json.loads(self.state_path.read_text()))

    def configure(self, config):
        config = validate_config(config)
        if config['bind_ip'] not in local_ipv4s():
            raise ValueError('Listen IP is not assigned to this VPS. Choose an address shown by ip -4 addr.')
        with socket.create_connection(('127.0.0.1', 22), timeout=3):
            pass
        ensure_keys(self.root, self.server)
        previous = {path: path.read_bytes() if path.exists() else None for path in (self.state_path, self.unit)}
        was_active = service('is-active', check=False).returncode == 0
        was_enabled = service('is-enabled', check=False).returncode == 0
        # Backups never contain a newly generated private key or rotate existing keys.
        backup = self.root / ('backup-' + dt.datetime.now(dt.timezone.utc).strftime('%Y%m%dT%H%M%S%fZ'))
        backup.mkdir(mode=0o700)
        for path, data in previous.items():
            if data is not None:
                atomic(backup / path.name, data)
        service('stop', check=False)
        try:
            with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
                sock.bind((config['bind_ip'], 53))
            atomic(self.state_path, (json.dumps(config, indent=2) + '\n').encode())
            atomic(self.unit, UNIT_TEXT.encode(), 0o644)
            subprocess.run(['systemctl', 'daemon-reload'], check=True, timeout=30)
            service('enable')
            service('start')
            time.sleep(1)
            service('is-active')
            udp_probe(config['zone'], config['bind_ip'])
            tunnel_banner(config, self.root, self.client)
        except Exception:
            service('stop', check=False)
            for path, data in previous.items():
                if data is not None:
                    atomic(path, data, 0o644 if path == self.unit else 0o600)
                else:
                    path.unlink(missing_ok=True)
            subprocess.run(['systemctl', 'daemon-reload'], check=True, timeout=30)
            service('enable' if was_enabled else 'disable', check=False)
            if was_active:
                service('start', check=False)
            raise

    def info(self):
        config = self.load()
        print('DNS zone: {zone}\nNameserver: {nameserver}\nPublic IPv4: {public_ip}\nListen: {bind_ip}:53/udp\nMTU: {mtu}'.format(**config))
        print('Required records at your DNS provider (DNS-only, never proxied):')
        print('  A   {nameserver} -> {public_ip}\n  NS  {zone} -> {nameserver}'.format(**config))
        print('No CNAME/A/AAAA record at the delegated tunnel zone. Remove stale AAAA at the nameserver.')
        print('Public key: ' + read_key(self.root / 'server.pub').hex())
        print('Client (public key file copied to client):')
        print('  dnstt-client -udp 1.1.1.1:53 -pubkey-file server.pub {} 127.0.0.1:7000'.format(config['zone']))
        print('  dnstt-client -doh https://cloudflare-dns.com/dns-query -pubkey-file server.pub {} 127.0.0.1:7000'.format(config['zone']))
        print('  ssh -p 7000 YOUR_SSH_USER@127.0.0.1')
        print('Local port 7000 is an SSH tunnel endpoint, NOT a SOCKS proxy. Use a dnstt-compatible client.')

    def diagnose(self, resolver):
        config = self.load()
        self.info()
        passed = True
        checks = [('systemd service', lambda: service('is-active')),
                  ('public/private key match', lambda: ensure_keys(self.root, self.server)),
                  ('local authoritative UDP response', lambda: udp_probe(config['zone'], config['bind_ip'])),
                  ('LOCAL authenticated DNS tunnel to SSH', lambda: tunnel_banner(config, self.root, self.client)),
                  ('PUBLIC resolver -> delegation -> authenticated SSH tunnel',
                   lambda: tunnel_banner(config, self.root, self.client, resolver + ':53', timeout=20))]
        for label, check in checks:
            try:
                check()
                print('PASS: ' + label)
            except (OSError, ValueError, subprocess.SubprocessError) as exc:
                passed = False
                print('FAIL: {}: {}'.format(label, exc))
        for record, kind in ((config['nameserver'], 'A'), (config['nameserver'], 'AAAA'), (config['zone'], 'NS')):
            print('\nResolver {}: {} {}'.format(resolver, record, kind), flush=True)
            subprocess.run(['dig', '+time=3', '+tries=1', '@' + resolver, record, kind], timeout=10, check=False)
        print('\nIf LOCAL passes but PUBLIC fails: check NS delegation, DNS-only A record, stale AAAA,')
        print('provider firewall UDP 53, resolver filtering, and propagation. A local pass does not prove public reachability.')
        print('For delegation troubleshooting: dig +trace {} NS'.format(config['zone']))
        return passed


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    commands = ap.add_subparsers(dest='command', required=True)
    for name in ('setup', 'info', 'serve'):
        commands.add_parser(name)
    configure = commands.add_parser('configure')
    for field in ('zone', 'nameserver', 'public-ip', 'bind-ip'):
        configure.add_argument('--' + field, required=True)
    configure.add_argument('--mtu', type=int, default=1232)
    diagnose = commands.add_parser('diagnose')
    diagnose.add_argument('--resolver', default='1.1.1.1')
    args = ap.parse_args()
    if os.geteuid() != 0:
        print('Run ragnar-dns as root.', file=sys.stderr)
        return 1
    os.umask(0o077)
    manager = DNSManager()
    try:
        ROOT.mkdir(parents=True, exist_ok=True, mode=0o700)
        ROOT.chmod(0o700)
        if args.command == 'serve':
            config = manager.load()
            # Read-only key verification under ProtectSystem=strict.
            if derive_public(read_key(ROOT / 'server.key')) != read_key(ROOT / 'server.pub'):
                raise ValueError('Public/private DNS tunnel keys do not match.')
            os.execv(SERVER, server_args(config))
        with (ROOT / '.lock').open('a') as lock:
            fcntl.flock(lock, fcntl.LOCK_EX)
            if args.command == 'info':
                manager.info()
            elif args.command == 'diagnose':
                return 0 if manager.diagnose(ipv4(args.resolver)) else 1
            else:
                if args.command == 'setup':
                    old = manager.load() if manager.state_path.exists() else {}
                    zone = input('Full tunnel zone [{}]: '.format(old.get('zone', 't.example.com'))).strip() or old.get('zone', '')
                    ns = input('Nameserver outside tunnel zone [{}]: '.format(old.get('nameserver', 'ns.example.com'))).strip() or old.get('nameserver', '')
                    public = input('VPS public IPv4 [{}]: '.format(old.get('public_ip', ''))).strip() or old.get('public_ip', '')
                    addresses = local_ipv4s()
                    print('Local IPv4 addresses: ' + ', '.join(addresses))
                    default = old.get('bind_ip', public if public in addresses else (addresses[0] if addresses else ''))
                    bind = input('Local listen IPv4 [{}]: '.format(default)).strip() or default
                    mtu = input('DNS response MTU [1232]: ').strip() or '1232'
                    config = dict(zone=zone, nameserver=ns, public_ip=public, bind_ip=bind, mtu=int(mtu))
                else:
                    config = dict(zone=args.zone, nameserver=args.nameserver, public_ip=args.public_ip,
                                  bind_ip=args.bind_ip, mtu=args.mtu)
                print('DNS service will restart; existing DNS tunnels will disconnect. Keys are preserved.')
                manager.configure(config)
                print('LOCAL authenticated DNS-to-SSH test passed. Public DNS records/firewalls still need verification.')
                manager.info()
    except (ValueError, OSError, subprocess.SubprocessError, KeyError, EOFError) as exc:
        print('DNS operation failed: {}'.format(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main())
